# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-25 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='热榜标题')),
                ('href', models.CharField(max_length=200, verbose_name='链接')),
                ('label', models.CharField(max_length=20, verbose_name='量化标签')),
                ('tabs', models.CharField(max_length=20, verbose_name='属性标签')),
            ],
            options={
                'verbose_name': '热榜榜单信息',
                'verbose_name_plural': '热榜榜单信息',
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='来源类型')),
            ],
            options={
                'verbose_name': '来源类型',
                'verbose_name_plural': '来源类型',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='来源名称')),
                ('is_delete', models.BooleanField(default=0, verbose_name='是否删除')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotlist.Kind', verbose_name='来源类型')),
            ],
            options={
                'verbose_name': '数据来源',
                'verbose_name_plural': '数据来源',
            },
        ),
        migrations.AddField(
            model_name='hostlist',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotlist.Source', verbose_name='热榜来源'),
        ),
    ]
