# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-27 03:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostlist',
            name='tabs',
        ),
        migrations.AddField(
            model_name='source',
            name='lable',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='数据来源标签'),
        ),
        migrations.AlterField(
            model_name='source',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 27, 11, 2, 51, 963991), verbose_name='创建时间'),
        ),
    ]
