# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-26 06:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotlist', '0002_source_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='click_times',
            field=models.IntegerField(default=0, verbose_name='点击率'),
        ),
        migrations.AddField(
            model_name='source',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 26, 14, 32, 19, 88892), verbose_name='创建时间'),
        ),
    ]
